//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NAA.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Application
    {
        public int ApplicationId { get; set; }
        public int ApplicantId { get; set; }
        public string CourseName { get; set; }
        public int UniversityId { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Please enter a Personal Statement.")]
        [MinLength(10, ErrorMessage = "At least 10 Characters for the Statement")]
        [MaxLength(4000, ErrorMessage = "Too long ! No more than 4000 Characters.")]
        public string PersonalStatement { get; set; }

        [MaxLength(4000, ErrorMessage = "No more than 4000 Characters !")]
        public string TeacherReference { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Need Teacher Contact.")]
        [MinLength(10, ErrorMessage = "Please enter more information. At least 10 Characters.")]
        [MaxLength(200, ErrorMessage = "Too long ! No more than 200.")]
        public string TeacherContactDetails { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Offer Cannot be empty !")]
        [RegularExpression("C|P|U|R", ErrorMessage = "Only enter C/U/P/R ")]
        public string UniversityOffer { get; set; }
        public Nullable<bool> Firm { get; set; }
    }
}
