//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NAA.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Profile
    {
        public int ApplicantId { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Need Applicant Name!")]
        [MinLength(2, ErrorMessage = "At least 2 Characters!")]
        [MaxLength(50, ErrorMessage = "This is too long! Maximun is 50.")]
        [RegularExpression(@"^[a-zA-Z0-9'' ']+$", ErrorMessage = "Look not like a name !(No Special Characters)")]
        public string ApplicantName { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Need Address !")]
        [MaxLength(150, ErrorMessage = "This is too long! No more than 150.")]
        public string ApplicantAddress { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Need Phone Contact!")]
        [DataType(DataType.PhoneNumber)]
        [RegularExpression(@"^(\d{11})$", ErrorMessage = "Not a valid phone number. (Only 11 number!)")]
        public string Phone { get; set; }

        
        [Required(AllowEmptyStrings = false, ErrorMessage = "Can't be Empty!")]
        [MaxLength(100, ErrorMessage = "This is too long! No more than 100.")]
        [RegularExpression(@"^\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*$", ErrorMessage = "Email is not valid.(Check if any space?)")]
        public string Email { get; set; }
        public string UserId { get; set; }
    }
}
